### ISSUE TITLE
doesn't work when updated to slate 0.34.0

### ISSUE THREAD

**Issue by guodong** [SamyPesse/slate-prism#12]

**Comment by pierre-b** [comment]
An update would be great, this plugin is what I'm looking for actually...
Or any will to release the current Gitbook Editor in open source guys?
Thanks!

**Comment by Soreine** [comment]
Sorry for the lack of update. Since we have forked Slate (https://github.com/GitbookIO/slate), we are no longer maintaining this plugin for the upstream version.
I invite you to look for forks or ask for alternatives in Slate's Slack community
