### ISSUE TITLE
Not clear on how GetSyntax works?

### ISSUE THREAD

**Issue by Nantris** [SamyPesse/slate-prism#2]
Thanks for the amazing work you've been doing. I'm wondering about implementation. 

How would I configure this to work for syntax besides JavaScript?

**Comment by oyeanuj** [comment]
@Slapbox It seems that it is either getting the `node.data.syntax` when the plugin is being used, or using the default syntax, which is Javascript. It might be worth exploring how to use Prism's ability to auto-detect language and PR to this repo.

**Comment by Soreine** [comment]
The plugin accepts an option `getSyntax`, where you provide your own logic to retrieve/compute the syntax of a block.

If, like us, you store the syntax of code blocks as part of the block's data, you can use the provided example implementation:

```
const plugin = PluginPrism({
        onlyIn: ...,
        getSyntax: (node => node.data.get('syntax'))
});
```

If you would like to auto-detect the syntax based on `block.text`, this is where you could do that.
